### ISSUE TITLE
Unable to build current master

### ISSUE THREAD

**Issue by alexwhitman** [gnunn1/terminix#310]
I've got the latest master branch checked out and building results in the following:
```
alex@desktop:~/projects/terminix (master)$ dub build --force
Performing "debug" build using dmd for x86_64.
gtk-d:gtkd 3.3.1: building configuration "library"...
gtk-d:gstreamer 3.3.1: building configuration "library"...
gtk-d:gtkdgl 3.3.1: building configuration "library"...
gtk-d:sv 3.3.1: building configuration "library"...
gtk-d:vte 3.3.1: building configuration "library"...
terminix ~master: building configuration "default"...
source/gx/terminix/prefwindow.d(311,15): Error: no property 'clear' for type 'string[string]'
dmd failed with exit code 1.
```
No idea why calling `.clear()` on a `string[string]` would fail.

I'm attempting to build with v2.071.0 of dmd on Ubuntu 16.04.

**Comment by gnunn1** [comment]
Hmm, that's weird because I am using the same version and the clear method is is supported:

https://dlang.org/spec/hash-map.html#removing_keys

For now, I think you can actually remove that line with no negative consequence as it's just a safety thing in case in the future it's called multiple times.

**Comment by alexwhitman** [comment]
Scratch that.  After purging dmd, gdc etc and reinstalling, it now compiles.  Not sure what happened as I hadn't installed any updates recently.
